In [273]:
from decimal import Decimal,getcontext 
getcontext().prec = 4
def matxRound(M, decPts=4):
    return [[Decimal(str(round(num,decPts))) for num in row] for row in M]
#    [[round(i,decPts)for i in row]for row in M]
    

b = [[1.0000000,2.0023466,3,5], 
     [2,3,3,5], 
     [1,2,5,1]]
print matxRound(b)


[[Decimal('1.0'), Decimal('2.0023'), Decimal('3.0'), Decimal('5.0')], [Decimal('2.0'), Decimal('3.0'), Decimal('3.0'), Decimal('5.0')], [Decimal('1.0'), Decimal('2.0'), Decimal('5.0'), Decimal('1.0')]]


In [274]:
import decimal
getcontext().prec = 30
Decimal(0.1).quantize(Decimal('0.0000'))  

Decimal('0.1000')

In [182]:
import unittest
import numpy as np

from decimal import getcontext, Decimal, ROUND_HALF_UP

getcontext().prec = 40
getcontext().rounding=ROUND_HALF_UP


r,c = np.random.randint(low=1,high=5,size=2)
matrix = np.random.random((r,c))

def matxRound(m,decPts):
    m[:] = [[Decimal(str(round(num,decPts)))for num in row]for row in m]
        
    
mat =[[1.66666,0,0,0],
     [0,1,0,0],
     [0,0,1,0],
     [0,0,0,1]]
print mat

matxRound(mat,3)

print"test"
print mat







[[1.66666, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
test
[[Decimal('1.667'), Decimal('0.0'), Decimal('0.0'), Decimal('0.0')], [Decimal('0.0'), Decimal('1.0'), Decimal('0.0'), Decimal('0.0')], [Decimal('0.0'), Decimal('0.0'), Decimal('1.0'), Decimal('0.0')], [Decimal('0.0'), Decimal('0.0'), Decimal('0.0'), Decimal('1.0')]]


In [80]:
import unittest
import numpy as np

from decimal import *    
    
def test_matxRound(self):

    for decpts in range(10):
        r,c = np.random.randint(low=1,high=25,size=2)
        matrix = np.random.random((r,c))

        mat = matrix.tolist()
        dec_true = [[Decimal(str(round(num,decpts))) for num in row] for row in mat]       
       
            
        matxRound(mat,decpts)
        dec_test = [[Decimal(str(num)) for num in row] for row in mat]
      
            
        res = Decimal('0')
        for i in range(len(mat)):
            for j in range(len(mat[0])):
                res += dec_test[i][j].compare_total(dec_true[i][j])

                
                
mat =[[1.66666,0,0,0],
     [0,1,0,0],
     [0,0,1,0],
     [0,0,0,1]]

F
FAIL: test_matxRound (__main__.LinearRegressionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aixiaoxiao/Desktop/linear_algebra-master/test.py", line 34, in test_matxRound
    self.assertEqual(res,Decimal('0'),'Wrong answer')
AssertionError: Wrong answer

----------------------------------------------------------------------
Ran 1 test in 0.011s

FAILED (failures=1)


In [172]:
list=[1,2,3,4,5]
def change(l):
    l[:] = [i**2 for i in l]


change(list)
print list

[1, 4, 9, 16, 25]


In [183]:
1/15

0

In [184]:
1.0/15

0.06666666666666667

In [271]:
import unittest
import numpy as np

from decimal import *


def test_gj_Solve(self):

    for _ in range(2):
        r =3
        A = np.random.randint(low=-10,high=10,size=(r,r))
        b = np.arange(r).reshape((r,1))
        print'a= {}'.format(A) 
        print '\n'
        print'b= {}'.format(b)
        print'\n'

#             x = gj_Solve(A.tolist(),b.tolist(),epsilon=1.0e-8)

#             if np.linalg.matrix_rank(A) < r:
#                 self.assertEqual(x,None,"Matrix A is singular")
        
       
#             self.assertEqual(np.array(x).shape,(r,1),"Expected shape({},1), but got shape{}".format(r,np.array(x).shape))
#             Ax = np.dot(A,np.array(x))
#             loss = np.mean((Ax - b)**2)
            
#             self.assertTrue(loss<0.1,"Bad result.")
                
    

In [272]:
print test_gj_Solve(1)

a= [[ 0  9 -6]
 [-9 -8 -6]
 [-7 -8 -9]]


b= [[0]
 [1]
 [2]]


a= [[-5  6  0]
 [ 9 -4 -4]
 [ 1  2 -9]]


b= [[0]
 [1]
 [2]]


None


In [270]:
def printL(m):
    h = len(m)
    w = len(m[0])
    for i in range (0,h)[::-1]:
        print'gogogo'
        for j in range(0,i):
            for k in range (i,w)[::-1]:
                print'm[j][k]: {}'.format(m[j][k])
                print'm[j][i]: {}'.format(m[j][i])

                m[j][k] -= m[j][i]*m[i][k]
                print m
    return m       

A= [[1,1,5,2],
    [0,1,4,7],
    [0,0,1,8]]        

print printL(A)

gogogo
m[j][k]: 2
m[j][i]: 5
[[1, 1, 5, -38], [0, 1, 4, 7], [0, 0, 1, 8]]
m[j][k]: 5
m[j][i]: 5
[[1, 1, 0, -38], [0, 1, 4, 7], [0, 0, 1, 8]]
m[j][k]: 7
m[j][i]: 4
[[1, 1, 0, -38], [0, 1, 4, -25], [0, 0, 1, 8]]
m[j][k]: 4
m[j][i]: 4
[[1, 1, 0, -38], [0, 1, 0, -25], [0, 0, 1, 8]]
gogogo
m[j][k]: -38
m[j][i]: 1
[[1, 1, 0, -13], [0, 1, 0, -25], [0, 0, 1, 8]]
m[j][k]: 0
m[j][i]: 1
[[1, 1, 0, -13], [0, 1, 0, -25], [0, 0, 1, 8]]
m[j][k]: 1
m[j][i]: 1
[[1, 0, 0, -13], [0, 1, 0, -25], [0, 0, 1, 8]]
gogogo
[[1, 0, 0, -13], [0, 1, 0, -25], [0, 0, 1, 8]]


In [275]:
print 'a'

a
